---
- hosts: local
  tasks:
  - name: Install Misc Packages  
    become: true
    apt: 
      force_apt_get: true   
      state: present 
      update_cache: true
      name: 
        - gnome-tweaks
        - gnupg-agent
        - gparted
        - keepassx
        - openssh-server
        - sshuttle
        - pastebinit
        - rsnapshot
        - ubuntu-restricted-extras
        - vim
        - vlc
        - wireshark
        - synaptic
        - quassel-client
        - yubikey-personalization
        - rng-tools
        - tree
        - mediainfo
    register: apt_output

  - debug: var=apt_output

  - name: Install VPNs
    become: true
    apt: 
      force_apt_get: true   
      state: present 
      update_cache: true
      name: 
        - network-manager-vpnc-gnome
        - network-manager-openconnect-gnome  
    register: apt_output

  - debug: var=apt_output

  - name: Install Virtualization
    become: true
    apt: 
      force_apt_get: true   
      state: present 
      update_cache: true
      name: 
        - qemu-kvm
        - libvirt-clients
        - virt-manager
    register: apt_output

  - debug: var=apt_output

  - name: Install dev-tools
    become: true
    apt: 
      force_apt_get: true   
      state: present 
      update_cache: true
      name: 
        - build-essential
        - cscope 
        - elfutils 
        - libdw-dev 
        - libncurses5-dev 
        - manpages-dev 
        - devscripts 
        - git 
        - gitk 
        - git-email 
        - debhelper 
        - sbuild 
        - subversion 
        - sysstat 
        - ubuntu-dev-tools 
        - autoconf 
        - autotools-dev 
        - bison 
        - texinfo 
        - texi2html 
        - texlive-latex-base 
        - ghostscript 
        - texlive-fonts-recommended 
        - fakeroot 
        - kernel-wedge 
        - kernel-package 
        - dh-autoreconf 
        - dh-translations 
        - gobject-introspection 
        - dpatch 
        - pbuilder-scripts 
        - jq 
    register: apt_output

  - debug: var=apt_output

  - name: Install Graphics programs
    become: true
    apt: 
      force_apt_get: true   
      state: present 
      update_cache: true
      name: 
        - gimp
        - luminance-hdr
        - hugin
        - darktable
    register: apt_output

  - debug: var=apt_output

  - name: Install Power programs
    become: true
    apt: 
      force_apt_get: true   
      state: present 
      update_cache: true
      name: 
        - powertop
        - powerstat
    register: apt_output

  - debug: var=apt_output

  - name: Install Indeed Specific programs
    become: true
    apt:
      force_apt_get: true
      state: present
      update_cache: true
      name:
        - rpm
        - curl
        - python-is-python3
    register: apt_output

  - debug: var=apt_output

  - name: Install classic snap packages
    become: true
    snap:
      name:
        - slack
        - code
      state: present
      classic: yes
    register: snap_output

  - debug: var=snap_output

  - name: Install snap packages
    become: true
    snap:
      name:
        - zoom-client
        - spotify
      state: present
    register: snap_output

  - debug: var=snap_output

# # Download out of repo packages
#   - name: Download out of repo packages
#     become: true
#     get_url:
#       url:
#         - https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

#       dest: Downloads

#   - name: Install out of repo Packages
#     apt: 
#       state: present 
#       deb: 
#         - Downloads/google-chrome-stable_current_amd64.deb
#     register: apt_output

#   - debug: var=apt_output

# TODO Add install Chrome
# TODO Add install jetbrains toolbox
# TODO Add mysql-workbench-community
# change keybinding for ibus-setup emojis to super+e to avoid interfereing with ctrl+shift+e vert split for terminator.
#   Ref: https://bugs.launchpad.net/ubuntu/+source/terminator/+bug/1738500
